---
# cloud_controller_uri: api.vcap.me
service:
  name: couchdb
  version: "0.11.0"
  description: 'CouchDB NoSQL store'
  plans: ['free']
  default_plan: free
  tags: ['couchdb', 'couchdb-0.11.0', 'nosql']
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "0xdeadbeef"
mbus: nats://localhost:4222
logging:
  level: debug
pid: /var/vcap/sys/run/couchdb_service.pid
# allow_over_provisioning: false
