---
plan: free
local_db: sqlite3:/var/vcap/services/couchdb/couchdb_node.db
mbus: nats://localhost:4222
index: 0
base_dir: /var/vcap/services/couchdb/instances
couchdb_log_dir: /var/vcap/services/couchdb/logs
ip_route: 127.0.0.1
logging:
  level: debug
pid: /var/vcap/sys/run/couchdb_node.pid
capacity: 200
node_id: couchdb_node_1
migration_nfs: /mnt/migration
couchdb_install_path: /var/vcap/packages/couchdb
couchdb:
  host: 127.0.0.1
  port: 5984
  admin: admin
  adminpass: mysecretpassword
