---
cloud_controller_uri: api.vcap.me
ip_route: localhost
index: 0
token: changemarketplacetoken
mbus: nats://localhost:4222
logging:
  level: debug

pid: /var/vcap/sys/run/marketplace.pid

# node_timeout is required by base async gateway class. This is defined in #{marketplace}.yml
# since this value is specific to interactions with #{marketplace}

marketplace: appdirect

acls: [ "*@example.com" ]

refresh_interval: 300
