---
local_db: sqlite3:/var/vcap/services/memcached/memcached_node.db
mbus: nats://localhost:4222/
index: 0
base_dir: /var/vcap/services/memcached/instances
logging:
  level: debug
pid: /var/vcap/sys/run/memcached_node.pid
capacity: 50
node_id: memcached_node_1
memcached_server_path: memcached
memcached_memory: 16
port_range:
  first: 5000
  last: 25000
memcached_log_dir: /var/vcap/sys/log/memcached
max_clients: 500
memcached_timeout: 2
sasl_enabled: false

# z_interval: 30
