---
plan: free
capacity: 100
local_db: sqlite3:/var/vcap/services/gemstone/gemstone_node.db
mbus: nats://localhost:4222
base_dir: /var/vcap/services/gemstone/
index: 0
logging:
  level: debug
pid: /var/vcap/sys/run/gemstone_node.pid
node_id: gemstone_node_1
