---
cloud_controller_uri: api.vcap.me
service:
  name: gemstone
  version: '3.0.1'
  description: 'GemStone/S 64 Bit database service'
  plans: ['free']
  default_plan: free
  tags: ['gemstone', 'gemstone-3.0.1', 'objects']
ip_route: localhost
index: 0
token: 'swordfish'
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/gemstone_service.pid
node_timeout: 2
